require 'rake/testtask'

refactoring_steps = FileList.new('page_*')
test_list = []

refactoring_steps.each do |step|
    Rake::TestTask.new("test-#{step}") do |t|
	    t.libs = [File.expand_path(step)]
	    t.pattern = 'test/**/tc_*.rb'
	    t.warning = true
    end
    task step => ["test-#{step}"]
end
